version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: change_me
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d myapp_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      SECRET_KEY: dev-secret-key
      DEBUG: "1"
      POSTGRES_DB: myapp_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: change_me
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  pgdata: